on:
  push:
    branches:
      - dev
name: 🚀 Deploy website on push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          ref: dev
      # build
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run generate --if-present
      # deploy
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.dev_ftp_host }}
          username: ${{ secrets.dev_ftp_user  }}
          password: ${{ secrets.dev_ftp_password }}
          server-dir: ${{ secrets.ftp_server_dir }}
          local-dir: .output/public/
          protocol: ftps
          log-level: verbose
      # notifications
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
